/** Shown one at a time while a render or edit is in flight, so the wait feels shorter. */
export const ARCHITECTURE_FACTS: string[] = [
  "The Eiffel Tower grows about 15 cm taller in summer — the iron expands as it heats up.",
  "Venice is built on more than 100,000 wooden piles driven into the lagoon's clay and mud.",
  "The Pantheon in Rome still has the world's largest unreinforced concrete dome, poured almost 1,900 years ago.",
  "Burj Khalifa's tapering shape was inspired by the desert flower Hymenocallis and a regional spiral minaret.",
  "Antoni Gaudí modeled the arches of the Sagrada Família on hanging chains, flipped upright.",
  "The Sydney Opera House's shells were engineered as sections of one giant imaginary sphere so every tile could match.",
  "Fallingwater's cantilevered terraces extend nearly 5 metres past their supports with no visible columns.",
  "The Great Wall of China isn't one continuous wall — it's thousands of kilometres of connected and unconnected sections.",
  "Ancient Roman concrete self-heals over centuries: seawater reacts with its lime to grow new mineral crystals in cracks.",
  "The Shard's glass facade uses angled panes that never quite meet, letting the building breathe naturally.",
  "Chartres Cathedral's flying buttresses let its walls be filled with stained glass instead of solid stone.",
  "The Chrysler Building's stainless-steel spire was secretly assembled inside the building and raised in 90 minutes.",
  "Japanese five-story pagodas often survive earthquakes because a central pillar sways independently, like a tuned mass damper.",
  "The Guggenheim Bilbao's titanium panels are only 0.3 mm thick — about three sheets of paper.",
  "Stonehenge's massive sarsen stones were shaped with interlocking joints borrowed from woodworking, not masonry.",
  "The Hoover Dam's concrete is still curing — engineers estimate it will fully cure in about 500 years.",
  "Taipei 101 uses a 660-tonne steel pendulum near the top to counteract sway from wind and earthquakes.",
  "The Colosseum could be shaded by a massive retractable awning, operated by sailors using a system of ropes and masts.",
  "Frank Lloyd Wright believed a building should \"grow\" from its site — he called the idea organic architecture.",
  "The Leaning Tower of Pisa's tilt was corrected in the 2000s by removing soil from under its raised side.",
  "Passive solar houses can be oriented so the low winter sun heats them, while summer's higher sun is blocked by the eaves.",
  "The world's tallest buildings sway several metres at the top in strong wind — occupants rarely notice.",
  "Rammed earth walls, one of the oldest building techniques, are seeing a revival for their natural insulation and low carbon footprint.",
  "The dome of Florence's cathedral was built without a wooden support frame — Brunelleschi invented new machines and a herringbone brick pattern instead.",
  "Green roofs can lower a building's summer cooling costs while also slowing stormwater runoff.",
  "The word \"skyscraper\" was originally a sailing term for the highest sail on a ship's mast.",
];
