import { Link } from "react-router-dom";
import { Banknote, Gauge, ReceiptText, TrendingDown } from "lucide-react";
import { Card, EmptyState, ErrorNote, StatCard, Table } from "../components/ui";
import { PageHero } from "../components/PageHero";
import { useAdminApi } from "../lib/api";
import { formatUsd } from "../lib/format";
import { navForPath } from "../lib/nav";
import { useLoad } from "../lib/useLoad";

export function FinancialsPage() {
  const api = useAdminApi(); const { data, error, reload } = useLoad(() => api.getFinancials(), [api], 30_000);
  const nav = navForPath("/financials");
  return <><PageHero title={nav.title} description={nav.description} image={nav.banner} />{error && <ErrorNote onRetry={reload}>{error}</ErrorNote>}{!data ? null : <div className="space-y-6">
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">Provider revenue is confirmed from captured payments. FAL cost is an internal estimate—not a provider wallet balance. Provider cost reconciliation: not connected.</div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="Net revenue" value={formatUsd(data.revenue.netUsd)} icon={Banknote} accent="emerald" /><StatCard label="Estimated FAL cost" value={formatUsd(data.estimatedCost.falUsd)} icon={Gauge} accent="amber" detail="Last 30 days; failed jobs excluded" /><StatCard label="MRR" value={formatUsd(data.revenue.mrrUsd)} icon={ReceiptText} accent="blue" /><StatCard label="Daily burn" value={formatUsd(data.estimatedCost.dailyBurnUsd)} icon={TrendingDown} accent="rose" detail={data.estimatedCost.projectedBudgetExhaustion ? `7-day rate · budget exhaustion: ${new Date(data.estimatedCost.projectedBudgetExhaustion).toLocaleDateString()}` : "7-day rate · forecast unavailable"} /></div>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Revenue health"><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-muted">Captured</dt><dd className="font-semibold">{formatUsd(data.revenue.capturedUsd)}</dd></div><div><dt className="text-muted">Refunded</dt><dd className="font-semibold">{formatUsd(data.revenue.refundedUsd)}</dd></div><div><dt className="text-muted">Failed payments</dt><dd className="font-semibold">{data.revenue.failedPayments}</dd></div><div><dt className="text-muted">Checkout conversion</dt><dd className="font-semibold">{(data.revenue.conversionRate * 100).toFixed(1)}%</dd></div><div><dt className="text-muted">Churned subscriptions</dt><dd className="font-semibold">{data.revenue.churnedSubscribers}</dd></div></dl></Card><Card title="Margin by product"><Margin rows={[...data.margins.byPlan, ...data.margins.byPack]} /></Card></div>
    <div className="grid gap-6 lg:grid-cols-2"><Card title="Estimated cost by model">{data.margins.byModel.length ? <Table head={["Model", "Renders", "Estimated cost"]}>{data.margins.byModel.map((row) => <tr key={row.label}><td className="px-5 py-3">{row.label}</td><td className="px-5 py-3">{row.renders}</td><td className="px-5 py-3">{formatUsd(row.estimatedCostUsd)}</td></tr>)}</Table> : <EmptyState>No tracked model costs.</EmptyState>}</Card><Card title="Customer margin"><Table head={["Customer", "Revenue", "Estimated cost", "Margin"]}>{data.margins.byCustomer.slice(0, 12).map((row) => <tr key={row.userId}><td className="px-5 py-3"><Link to={`/users/${row.userId}`} className="text-blueprint hover:underline">{row.email}</Link></td><td className="px-5 py-3">{formatUsd(row.revenueUsd)}</td><td className="px-5 py-3">{formatUsd(row.estimatedCostUsd)}</td><td className="px-5 py-3">{formatUsd(row.marginUsd)}</td></tr>)}</Table></Card></div>
  </div>}</>;
}
function Margin({ rows }: { rows: { label: string; revenueUsd: number; estimatedCostUsd: number; marginUsd: number }[] }) { return rows.length ? <Table head={["Product", "Revenue", "Est. cost", "Margin"]}>{rows.map((row) => <tr key={row.label}><td className="px-5 py-3">{row.label}</td><td className="px-5 py-3">{formatUsd(row.revenueUsd)}</td><td className="px-5 py-3">{formatUsd(row.estimatedCostUsd)}</td><td className="px-5 py-3">{formatUsd(row.marginUsd)}</td></tr>)}</Table> : <EmptyState>No captured product revenue.</EmptyState>; }
