import { FormEvent, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { DashboardSidebar } from "../dashboard/DashboardSidebar";
import { DashboardTopBar } from "../dashboard/DashboardTopBar";
import { useApiClient } from "../lib/apiClient";

export type SectionKey = "explore" | "templates" | "assets" | "ai-tools" | "team" | "settings" | "billing" | "activity";
const copy: Record<SectionKey, [string, string, string]> = {
  explore: ["Discover", "Explore architectural ideas", "A curated starting point for materials, moods, and presentation styles."], templates: ["Start faster", "Project templates", "Choose a proven visual direction, then make it your own in the Studio."], assets: ["Your library", "Assets and uploads", "Keep sketches, models, references, and finished renders in one place."], "ai-tools": ["Creative toolkit", "AI tools", "Focused workflows for rendering, regional edits, materials, and variations."], team: ["Collaboration", "Your team", "Invite collaborators and keep project feedback close to the work."], settings: ["Preferences", "Studio settings", "Control notifications, render defaults, and workspace behavior."], billing: ["Plans and usage", "Upgrade your workspace", "Pick the rendering capacity that fits the way you work."], activity: ["Workspace history", "Recent activity", "A clear record of projects, renders, uploads, and team changes."],
};
const cards: Partial<Record<SectionKey, Array<[string, string, string?]>>> = {
  explore: [["Warm minimal residences", "Natural timber, quiet stone, and generous daylight.", "/dashboard/house-exterior.jpg"], ["Modern lakeside living", "Low profiles and reflective landscapes.", "/dashboard/lakeside-house.jpg"], ["After-dark presentation", "Controlled contrast and believable interior light.", "/dashboard/house-dark.jpg"]],
  templates: [["Photoreal exterior", "Balanced daylight, landscaping, and natural materials.", "/style-thumbs/photorealistic.jpg"], ["Architectural linework", "Clean monochrome studies for early design reviews.", "/style-thumbs/vector-sketch.jpg"], ["Watercolor concept", "Soft atmospheric visuals for presentations.", "/style-thumbs/watercolor-sketch.jpg"]],
  "ai-tools": [["Sketch to render", "Turn linework into a presentation-ready visualization."], ["Regional material edit", "Change one surface while preserving the building."], ["Design variations", "Explore alternate finishes without redrawing the project."]],
};

export function DashboardSectionRoute({ section }: { section: SectionKey }) {
  const api = useApiClient(); const navigate = useNavigate(); const location = useLocation();
  const [notice, setNotice] = useState(""); const [search, setSearch] = useState(""); const [files, setFiles] = useState<string[]>([]); const [uploading, setUploading] = useState(false);
  const [eyebrow, title, description] = copy[section];
  const visibleCards = (cards[section] ?? []).filter(([name]) => name.toLowerCase().includes(search.toLowerCase()));
  const create = async (name = "Untitled project") => { const project = await api.createProject({ name }); navigate(`/project/${project.id}`); };
  const invite = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setNotice(`Invitation prepared for ${String(data.get("email"))}.`); event.currentTarget.reset(); };
  const upload = async (selected: FileList | null) => { const list = Array.from(selected ?? []); if (!list.length) return; setFiles(list.map((file) => file.name)); setUploading(true); try { for (const file of list) { const result = await api.uploadImage(file); await api.createReference({ url: result.publicUrl, source: "upload" }); } setNotice(`${list.length} ${list.length === 1 ? "file" : "files"} uploaded to your asset library.`); } catch { setNotice("The upload could not be completed. Check your connection and try again."); } finally { setUploading(false); } };
  return <div className="dashboard-shell"><DashboardSidebar view="home" activeSection={section} onChangeView={() => navigate("/dashboard")} onCreate={() => void create()}/><div className="dashboard-workspace"><DashboardTopBar value={search} onChange={setSearch} onNotifications={() => navigate("/activity")}/><main className="dashboard-feature-page">
    <button type="button" className="feature-back" onClick={() => navigate("/dashboard")}>← Dashboard</button><header><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></header>{notice && <div className="feature-notice" role="status">{notice}</div>}
    {visibleCards.length > 0 && <div className="feature-card-grid">{visibleCards.map(([name, text, image]) => <article key={name} className="feature-card">{image && <img src={image} alt=""/>}<div><h2>{name}</h2><p>{text}</p><button type="button" onClick={() => void create(name)}>Use this direction →</button></div></article>)}</div>}
    {section === "assets" && <section className="feature-form-card"><h2>Upload project files</h2><p>Choose images, drawings, or model exports before attaching them to a project.</p><label className="feature-upload"><input type="file" multiple autoFocus={location.search.includes("upload=1")} accept="image/*,.pdf,.dwg,.dxf,.skp" onChange={(event) => void upload(event.target.files)}/><span>{uploading ? "Uploading…" : "Choose files"}</span><small>PNG, JPG, PDF, DWG, DXF, or SKP</small></label>{files.length > 0 && <ul>{files.map((file) => <li key={file}>{file}</li>)}</ul>}</section>}
    {section === "team" && <form className="feature-form-card" onSubmit={invite}><h2>Invite a collaborator</h2><label>Email address<input name="email" type="email" placeholder="designer@studio.com" required/></label><label>Role<select name="role"><option>Editor</option><option>Viewer</option><option>Administrator</option></select></label><button type="submit">Prepare invitation</button></form>}
    {section === "settings" && <section className="feature-form-card feature-settings"><h2>Workspace preferences</h2><label><span>Email me when a render finishes<small>Useful for longer high-resolution jobs.</small></span><input type="checkbox" defaultChecked/></label><label><span>Preserve source geometry<small>Keep openings and structural lines fixed by default.</small></span><input type="checkbox" defaultChecked/></label><label><span>Default output<select defaultValue="2K"><option>1K</option><option>2K</option><option>4K</option></select></span></label><button type="button" onClick={() => { localStorage.setItem("renvia.studio.preferencesSavedAt", new Date().toISOString()); setNotice("Your workspace preferences were saved."); }}>Save preferences</button></section>}
    {section === "billing" && <div className="feature-plan-grid"><Plan name="Starter" price="$0" detail="5 renders each month, 720p exports, and one project."/><Plan name="Studio" price="$29" detail="200 monthly renders, 4K output, and unlimited projects." featured onChoose={() => setNotice("Studio selected. Secure checkout will open when billing is connected.")}/><Plan name="Enterprise" price="Custom" detail="Team collaboration, private storage, and dedicated support." onChoose={() => setNotice("Enterprise selected. Your workspace request is ready for sales follow-up.")}/></div>}
    {section === "activity" && <div className="feature-activity-list">{["You edited Project (2)","Lakeside Villa render completed","Modern Residence was created","Apartment Interior file uploaded","Workspace preferences updated"].map((item, index) => <article key={item}><span>{index + 1}</span><div><strong>{item}</strong><small>{index === 0 ? "5 days ago" : `${index + 1} weeks ago`}</small></div></article>)}</div>}
  </main></div></div>;
}
function Plan({ name, price, detail, featured, onChoose }: { name: string; price: string; detail: string; featured?: boolean; onChoose?: () => void }) { const current = name === "Starter"; return <article className={`feature-plan ${featured ? "is-featured" : ""}`}><p>{featured ? "Most popular" : "Renvia"}</p><h2>{name}</h2><strong>{price}{price.startsWith("$") && <small>/month</small>}</strong><span>{detail}</span><button type="button" disabled={current} onClick={onChoose}>{current ? "Current plan" : name === "Enterprise" ? "Contact sales" : `Choose ${name}`}</button></article>; }
