export interface ArticleSection { title: string; paragraphs: string[]; points?: string[]; }
export interface Article { slug: string; category: string; title: string; dek: string; date: string; readTime: string; image: string; imageAlt: string; takeaway: string; sections: ArticleSection[]; }

export const ARTICLES: Article[] = [
  { slug: "architectural-rendering-workflow", category: "Workflow", title: "From elevation drawing to a presentation-ready render", dek: "A practical workflow for turning raw architectural linework into a believable visual without losing the design decisions that matter.", date: "September 9, 2026", readTime: "7 min read", image: "/hero/lakeside-house.jpg", imageAlt: "A photorealistic modern house beside a lake", takeaway: "The strongest render is not the one with the most effects. It is the one that communicates the design clearly while keeping geometry, materials, and light coherent.", sections: [
    { title: "Begin with a source image the model can read", paragraphs: ["A clean elevation or perspective gives the renderer fewer decisions to invent. Remove stray dimensions, overlapping annotations, and marks that could be mistaken for façade elements. Keep openings, roof edges, and primary material boundaries clear.", "Export at a useful resolution and avoid crushing fine linework. If a window mullion disappears in the source, no prompt can reliably bring back the exact design later."], points: ["Use one consistent camera or projection system.", "Keep the full building inside the frame.", "Name each elevation before upload."] },
    { title: "Lock the design before styling it", paragraphs: ["Treat geometry and appearance as separate layers. First confirm that the massing, window count, doors, balconies, and roof form are correct. Only then introduce cladding, planting, lighting, and atmosphere.", "This sequence makes revisions legible. When a result drifts, you can identify whether the problem came from structure, material direction, or presentation rather than changing everything at once."] },
    { title: "Describe materials as systems", paragraphs: ["A useful material prompt explains more than colour. Include scale, finish, joint pattern, weathering, and where the material belongs. ‘Warm timber’ is vague; ‘vertical natural oak battens with narrow shadow gaps on the upper volume’ gives the system a boundary and construction logic."] },
    { title: "Finish with light, landscape, and people", paragraphs: ["Presentation elements should support the architecture. Use planting to frame entrances and soften edges, not to hide unresolved façades. Pick a time of day that explains the building: clear daylight for material accuracy, or early evening when interior lighting and occupation matter.", "Before export, compare the final image against the source drawing. The render should feel richer, but the project should still be unmistakably yours."] },
  ]},
  { slug: "consistent-four-elevation-renders", category: "Best practices", title: "How to keep four elevation renders consistent", dek: "Materials, lighting, and architectural details often drift from one view to the next. A shared visual brief keeps every side of the building in the same world.", date: "September 9, 2026", readTime: "6 min read", image: "/studio/elevation-front.jpg", imageAlt: "Rendered front elevation of a modern residence", takeaway: "Consistency comes from shared constraints: one material schedule, one lighting condition, one landscape language, and an explicit list of geometry that cannot change.", sections: [
    { title: "Create one visual brief for the whole building", paragraphs: ["Write the brief once and reuse it across front, rear, left, and right views. It should define the project’s main materials, glazing character, roof finish, landscape type, weather, and time of day.", "Avoid rewriting the prompt from memory for every elevation. Small wording changes can create large visual differences, especially in colour temperature and material scale."], points: ["Primary and secondary façade materials", "Window frame colour and reflectivity", "Ground treatment and planting palette", "Weather, sun direction, and time of day"] },
    { title: "Use the first approved image as the benchmark", paragraphs: ["Choose the clearest elevation for the first render. Refine it until the material balance and atmosphere are right, then use that image as a visual reference for the remaining sides.", "The benchmark is not permission to copy geometry from the first view. It is a source for colour, texture, lighting, and presentation language while each elevation keeps its own structure."] },
    { title: "Protect architectural invariants", paragraphs: ["List what must never change: opening count, roof pitch, balcony depth, column positions, and major edges. These constraints are especially important on elevations with fewer visual cues, where an AI model may otherwise simplify or embellish the design."] },
    { title: "Review the set, not isolated images", paragraphs: ["Place all four results side by side and compare the same elements across views. Check whether a cladding band wraps the corner, whether roof edges share one finish, and whether the landscape belongs to the same site.", "A coherent set is more valuable than four individually dramatic images. Resolve mismatches before increasing resolution or adding final presentation effects."] },
  ]},
  { slug: "better-architectural-ai-prompts", category: "Prompting", title: "Write architectural AI prompts that produce usable results", dek: "Move beyond adjective lists. A clear hierarchy of intent, constraints, materials, and atmosphere gives the renderer a job it can actually follow.", date: "September 9, 2026", readTime: "8 min read", image: "/studio/elevation-side-a.jpg", imageAlt: "Side elevation render of a contemporary home", takeaway: "A professional prompt reads like a concise design brief: what is being shown, what must remain fixed, what may change, and how the finished image should communicate the project.", sections: [
    { title: "Start with the task, not the mood", paragraphs: ["Open with the transformation you want: render an uploaded elevation, replace one façade material, or create a dusk variation from an approved daylight image. This gives every detail that follows a clear purpose.", "Then name the project type and view. A residential front elevation needs different assumptions from an interior lobby or an aerial masterplan."], points: ["Task and source image", "Project type and camera view", "Elements that must remain unchanged", "Material and environmental direction", "Desired presentation quality"] },
    { title: "Separate constraints from creative direction", paragraphs: ["Constraints protect the design: preserve all openings, do not alter the roof, keep the camera fixed. Creative direction controls the finish: pale limestone, dark bronze frames, restrained tropical planting, overcast daylight.", "Keeping these ideas separate makes the prompt easier to debug. If geometry changes, strengthen the constraint block. If the image feels generic, improve the material and atmosphere block."] },
    { title: "Use observable language", paragraphs: ["Describe things that can appear in an image. Replace ‘luxurious’ with honed limestone, deep window reveals, warm concealed lighting, and carefully spaced planting. Replace ‘futuristic’ with a specific structural or material quality.", "Observable language reduces ambiguity and gives you details you can evaluate against the result."] },
    { title: "Iterate one variable at a time", paragraphs: ["Once the composition is working, change only one category per iteration. Test the stone finish, then planting density, then light. If every variable changes together, it becomes impossible to know which instruction improved or damaged the image.", "Save the prompt with the approved render. It becomes part of the project record and a reliable starting point for later elevations and revisions."] },
  ]},
];

export function getArticle(slug: string) { return ARTICLES.find((article) => article.slug === slug); }
